theme: jekyll-theme-cayman
title:WP + Accessibility
description:This Docker+Wordpress project brings you some the basic standards for accessibility (A, AA) you must follow to get basic accessibility W3C standard, please include them in your daily programming culture.
