theme: jekyll-theme-cayman
title: WP + Accessibility
description: This Docker+Wordpress project will bring you some basic standards for accessibility (A, AA) <br>
and you must follow to get basic accessibility W3C standard, <br>
please include them in your daily programming culture.
